server:
  port: ${PORT:0}

spring:
  application:
    name: api-catalog
    data:
      mongodb:
        username: root
        password: root
        database: 'catalogdb'
        port: 27017
        host: localhost

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}